name: Sync with Hugging Face Hub

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/sync-with-huggingface.yml
      - examples/custom_pipeline/**
      - src/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Sync with Hugging Face
      uses: nateraw/huggingface-sync-action@v0.0.4
      with:
        github_repo_id: nateraw/closedai
        huggingface_repo_id: nateraw/custom-pipeline-server
        repo_type: space
        space_sdk: docker
        subdirectory: examples/custom_pipeline
        hf_token: ${{ secrets.HF_TOKEN }}
